### PR TITLE
added projects component

### PR DESCRIPTION
**Pull request by Sharjeel-Afridi**
image

Title, description, image, link and source code link are given as props to the component.

### CODE REVIEW

**Comment by SumirVats2003** [comment]
Good work until now, reviewed your code. Here are the pointers(in descending order of priority):

1. The project card is inconsistent. It looks alright in your view, but is not the same everywhere.
Screenshot 2024-01-27 183136

2. The organization images squeeze in mobile view.
Screenshot 2024-01-27 183744

3. Use `react-router` for routing instead of the `window` object [src/Components/ProjectCard.jsx]

4(a). Add a line break after each CSS styling rule for example:
```css
styling-one {
  /* style rules */
}
/* This line break is important - keep this line empty*/
styling-two {
  /* style rules */
}
```

4(b). Stick with the project's indentation rule. Use 2 spaces as an indent level

I will let you know about the projects that are to be included, and some format change in the card [a very subtle one]. Until then, fix the above issues

**Comment by Sharjeel-Afridi** [comment]
I have made the specified changes. please check!

**Review by SumirVats2003 — COMMENTED** [review]
Good work. Following pointers noticed:
1. The button `className` in the `ProjectCard` component is set as `source-btn` which must be changed to `btn` for consistency.
2. Remember to change indentation as specified in the last comment in the `css` and `jsx` files.

**Review by SumirVats2003 — COMMENTED** [review]
```
<Link to={codelink}>
<button className="source-btn" onClick={() => {handleClick(codelink)}}>Source Code</button>
</Link>
```
In this piece of code, you have used both `Link` and `onClick`.
When using `Link`, you should remove the `onClick` event listener.
Check the `Home` page code on how to handle linking of pages.

**Comment by Sharjeel-Afridi** [comment]
made some changes, please check.

**Review by SumirVats2003 — COMMENTED** [review]
DO NOT override the `btn` css class.

**Review by SumirVats2003 — APPROVED** [review]
LGTM, Merging

**Pull request merged**
